[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
gateway_settlement = "92xJg6zJM8Rh8bPDnpuX1PxSnVJ1dojodsE1dSJqNAHh"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
